### PR TITLE
Add error pages

### LINKED ISSUE #109: Error component
Build a React component that renders a javascript `Error` object into HTML. The view shall display a pictogram that is ~25% of the width of the parent container. Below the pictogram is the error message displayed.  
The following types of errors are handled with special pictograms:
* NotFound
* NetworkError
* CancellationError

### PR DESCRIPTION
**Pull request by derwehr**
Draft for adding error pages. Text and images will be replaced.

### CODE REVIEW

**Review by CatoLeanTruetschel — CHANGES_REQUESTED** [review]
The error components/pages are all essentially the same. Combine them to a single component and switch by error type in the component. The error type (an enum value or a js error object or both) is then a paramter that can be passed from outside.

**Comment by CatoLeanTruetschel** [comment]
Changed the base branch to main, as of our new branching strategy.

**Comment by derwehr** [comment]
> The error components/pages are all essentially the same. Combine them to a single component and switch by error type in the component. The error type (an enum value or a js error object or both) is then a paramter that can be passed from outside.

Done.
A parameter of type `Error` will probably get added with the implementation of error boundaries (#112) to then render this component with js errors as parameter, too.

**Review by CatoLeanTruetschel — APPROVED** [review]
This looks very good. There are some minor points that can be done in the future in a follow up PR.

When a JS error is specified, but no error type. This always renders a generic error even if the JS error has a specific, known error type. #144 

The image and text should be centered in the view #143

**Pull request merged**
