### PR TITLE
added eslint and prettier configs

### PR DESCRIPTION
**Pull request by derwehr**
Added ESLint and Prettier configs, (and extended the dev-dependencies in package.json) as discussed in #3.

(Ready for review)

### CODE REVIEW

**Comment by CatoLeanTruetschel** [comment]
You did not set a reviewer and we currently have no team standards on who will review then. Do you have someone in mind who you want to review this, or shall I?

**Comment by derwehr** [comment]
> You did not set a reviewer and we currently have no team standards on who will review then. Do you have someone in mind who you want to review this, or shall I?

Don't have anyone in mind, so if you (or anyone else) have time to do so please review. On our next meeting I guess we'll have to establish a standard for who reviews which issue.

**Comment by CatoLeanTruetschel** [comment]
LGTM

**Review by CatoLeanTruetschel — APPROVED** [review]

**Comment by derwehr** [comment]
this pr has been manually merged by 05e82b420bcd6b38f75d5cd4dc9acad9a78e3536
and linting according to new config was done by 5fdf9b8f0badba62f880d09973ac441818af5900,
except for code concerning the randomnumbergenerator, as this is not intended to stay anyways.

**Pull request closed without merging**
